config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # root_url is needed for Devise Gem.
  # root to: "home#index"
  root "home#index"
  resources :users
  get "users/:name", to: "users#show", as: "profile"

  resources :posts
  get '/posts', to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	
	validates :content, presence: true
    validates :quantity, presence: true
    validates :price, presence: true
    validates_inclusion_of :btc, :in => [true, false]

end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    # Force users to login before doing anything.
    before_action :authenticate_user!

end

app/controllers/cryptocurrencys_controller.rb
class CryptocurrencysController < ApplicationController
  def fetch
    cryptocurrency = Cryptocurrency.find_by name: 'btc'
    if cryptocurrency.name == "btc"
      response = Faraday.get "https://api.coinmarketcap.com/v1/ticker/bitcoin/"
      response = JSON.parse(response.body)[0]
      @name = "Bitcoin"
    else
      response = Faraday.get "https://api.coinmarketcap.com/v1/ticker/ethereum/"
      response = JSON.parse(response.body)[0]
      @name = "Ethereum"
    end
    @price = response["price_usd"].to_f
    @marketcap = response["market_cap_usd"].to_f
    @volume = response["24h_volume_usd"].to_f
    cryptocurrency.update(marketcap: @marketcap, price: @price, volume: @volume)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    fetch
  end

  def fetch
    bitcoin = Cryptocurrency.find_by name: "btc"
    response = Faraday.get "https://api.coinmarketcap.com/v1/ticker/bitcoin/"
    response = JSON.parse(response.body)[0]
    @bname = "Bitcoin"
    @bprice = response["price_usd"].to_f
    @bmarketcap = response["market_cap_usd"].to_f
    @bvolume = response["24h_volume_usd"].to_f
    @bchange = response["percent_change_1h"].to_f
    bitcoin.update(marketcap: @bmarketcap, price: @bprice, volume: @bvolume)

    ethereum = Cryptocurrency.find_by name: "eth"
    response = Faraday.get "https://api.coinmarketcap.com/v1/ticker/ethereum/"
    response = JSON.parse(response.body)[0]
    @ename = "Ethereum"
    @eprice = response["price_usd"].to_f
    @emarketcap = response["market_cap_usd"].to_f
    @evolume = response["24h_volume_usd"].to_f
    @echange = response["percent_change_1h"].to_f
    ethereum.update(marketcap: @emarketcap, price: @eprice, volume: @evolume)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:destroy, :show, :edit, :update]

  def index
    @posts = Post.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
  	if params[:post][:btc] == "true"
			btc_param = true
  	else
  		btc_param = false
		end
    @post = Post.new(content: params[:post][:content], quantity: params[:post][:quantity].to_f, price: params[:post][:price].to_f, btc: btc_param)
    @post.user_id = current_user.id
    if @post.save!
    	redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(story_params)
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
    else
      flash[:error] = 'Cannot delete this post...'
    end
    redirect_to posts_path
  end

  def show
  end

  private

  def post_params
    params.require(:post).permit(:btc, :content, :quantity, :price)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptocurrencys_helper.rb
module CryptocurrencysHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="row text-center">
  <h2>Market Stats</h2>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th class="text-center">CryptoCurrency</th>
        <th class="text-center"><%= @bname %></th>
        <th class="text-center"><%= @ename %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Market Cap</td>
        <td>$<%= number_with_delimiter(@bmarketcap, :delimiter => ',') %></td>
        <td>$<%= number_with_delimiter(@emarketcap, :delimiter => ',') %></td>
      </tr>
      <tr>
        <td>24-Hour Volume</td>
        <td>$<%= number_with_delimiter(@bvolume, :delimiter => ',') %></td>
        <td>$<%= number_with_delimiter(@evolume, :delimiter => ',') %></td>
      </tr>
      <tr>
        <td>Price</td>
        <% if @bchange > 0 %>
          <td><font color="#2cf400">$<%= number_with_delimiter(@bprice, :delimiter => ',') %></font></td>
        <% else %>
          <td><font color="#f40000">$<%= number_with_delimiter(@bprice, :delimiter => ',') %></font></td>
        <% end %>
        <% if @echange > 0 %>
          <td><font color="#2cf400">$<%= number_with_delimiter(@eprice, :delimiter => ',') %></font></td>
        <% else %>
          <td><font color="#f40000">$<%= number_with_delimiter(@eprice, :delimiter => ',') %></font></td>
        <% end %>
      </tr>
    </tbody>
  </table>
<!-- Button to refresh the page. -->
<!-- Use the code below to only use JS. -->
  <!-- <form class="btn btn-block">
      <input type="button" onclick="history.go(0)" value="Refetch Data">
  </form> -->
  <p><%= link_to "Refresh Market Data", root_path, class: 'btn btn-primary btn-large' %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptus</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <style>
      .pad {padding-top: 20px;}
    </style>
    <!-- Needed for Devise Gem. -->
    <% if notice %>
      <p><%= notice %></p>
    <% end %>

    <!-- Needed for Devise Gem. -->
    <% if alert %>
      <p><%= alert %></p>
    <% end %>

    <div class="container text-right pad">
      <p>
        <%= link_to 'Home', root_path, :class => 'navbar-link' %> |
        <% if user_signed_in? %>
            Logged in as <strong><%= link_to "#{current_user.email}", profile_path(current_user), :class => 'user navbar-link' %></strong>.  |
          <%= link_to 'Cryptus Marketplace', posts_path, :class => 'navbar-link' %>   |
          <%= link_to 'My profile', profile_path(current_user), :class => 'user navbar-link' %>   |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>   |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>   |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>

    <div class="btn btn-block">
      <h1><%= link_to "Cryptus", root_path %></h1>
    </div>
    <hr>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for Post.new do |p| %>

  <div class="form-group">
    <%= p.label :content %>
    <%= p.text_field :content, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= p.label :quantity %>
    <%= p.text_field :quantity, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= p.label :price %>
    <%= p.text_field :price, class: 'form-control', required: true%>
  </div>

  <div class="form-group">
    <%= p.label "CryptoCurrency" %>
    <div class="justify-left">
      <p>Bitcoin <%= p.radio_button :btc, true %></p>
      <p>Ethereum <%= p.radio_button :btc, false %></p>
    </div>
  </div>

  <%= p.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit post </h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2> Cryptus Marketplace </h2>

<div class="pad">
  <p><%= link_to 'New Post', new_post_path, class: 'btn btn-primary btn-large' %></p>
</div>

<div class="pad">
<% @posts.each do |post| %>
  <div class="well well-lg pad">
    <!-- <h2><%= link_to post.content, post_path(post) %></h2> -->
    <p>Description: <%= post.content%> </p>
    <% if post.btc == true %>
    	<p>Type: Bitcoin</p>
    <% else %>
    	<p>Type: Ethereum</p>
    	<% end %>
    <p>Quantity: <%= post.quantity %></p>
    <p>Price: <%= post.price %></p>

    <% if post.user_id == current_user.id %>
      <div class="btn-group">
        <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info' %>
        <%= link_to 'Delete', post_path(post), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger' %>
      </div>
    <% else %>
      <div class="btn-group">
        <%= link_to 'Contact seller!', profile_path(post.user_id), class: 'btn btn-info' %>
        </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h2>New Post </h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<% @post.content %>

<p><%= @post.content %></p>

<div class="btn-group">
  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-info' %>
  <%= link_to 'Delete', post_path(@post), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class="pad"><%= link_to "Log in", new_session_path(resource_name), class: "btn btn-info btn-large" %></div><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="pad"><%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-info btn-large" %></div><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class="pad"><%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-info" %></div><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <div class="pad"><%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "btn btn-info btn-large" %></div><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <div class="pad"><%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn btn-info btn-large" %></div><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <div class="pad"><%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-info btn-large" %></div><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h2> <%= @user.name %>'s Profile</h2>

<table class="table table-bordered table-hover text-center pad">
  <tbody>
    <tr>
      <td><strong>Email</strong></td>
      <td><%= @user.email if @user.email %></td>
    </tr>
    <tr>
      <td><strong>Name</strong></td>
      <td><%= @user.name if @user.name %></td>
    </tr>
    <tr>
      <td><strong>Description</strong></td>
      <td><%= @user.description if @user.description %></td>
    </tr>
  </tbody>
</table>
<h3><%= @user.name %>'s Sale Posts</h3>
<div class="pad">
  <% @user.posts.each do |post| %>
    <div class="well well-lg pad">
      <p>Title: <%= post.content%> </p>
      <% if post.btc == true %>
      	<p>Type: Bitcoin</p>
      <% else %>
      	<p>Type: Ethereum</p>
      	<% end %>
      <p>Quantity: <%= post.quantity %></p>
      <p>Price: <%= post.price %></p>

      <% if post.user_id == current_user.id %>
        <div class="btn-group">
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info' %>
          <%= link_to 'Delete', post_path(post), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<p><%= link_to "Back To Home Page", root_path, class: "btn btn-primary btn-large" %></p>